In [26]:
import numpy as np
import pandas as pd

**Question 1**

What's the version of Pandas that you installed?

You can get the version information using the \__version__ field:

In [52]:
# Get Pandas version
pd.__version__

'2.0.3'

In [54]:
# Download California Housing Prices dataset
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-14 20:56:07--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8003::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1,4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1,36M  3,65MB/s    in 0,4s    

2023-09-14 20:56:08 (3,65 MB/s) - ‘housing.csv’ saved [1423529/1423529]



In [56]:
#Use the 'pd.read_csv()' function to read the data from a CSV file
df = pd.read_csv('housing.csv')
# Display the first 5 rows
df.head(n=5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

**Question 2**

How many columns are in the dataset?

In [57]:
# Get number of columns
df.shape[1]

10

**Question 3**

Which columns in the dataset have missing values?

In [58]:
# Calculate the count of missing values for each column
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

**Question 4**

How many unique values does the ocean_proximity column have?

In [59]:
# Get unique value for ocean_proximity column
unique_values_count = df['ocean_proximity'].nunique()
unique_values_count

5

**Question 5**

What's the average value of the median_house_value for the houses located near the bay?

In [62]:
# Select rows in the DataFrame 'df' where 'ocean_proximity' is 'NEAR BAY' and store it in 'near_bay_df'.
near_bay_df = df[df['ocean_proximity'] == 'NEAR BAY']
#Calculate the average of the 'median_house_value' column
average_median_house_value_near_bay = near_bay_df['median_house_value'].mean()
average_median_house_value_near_bay

259212.31179039303

**Question 6**

1. Calculate the average of total_bedrooms column in the dataset.
2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
3. Now, calculate the average of total_bedrooms again.
4. Has it changed?

Has it changed?

In [67]:
# Calculate the average of total_bedrooms column
average_before_filling = df['total_bedrooms'].mean()
average_before_filling

537.8705525375617

In [68]:
#mean_total_bedrooms = df['total_bedrooms'].mean()
df['total_bedrooms'].fillna(average_before_filling, inplace=True)

In [69]:
average_after_filling = df['total_bedrooms'].mean()
average_after_filling

537.8705525375617

In [70]:
average_before_filling == average_after_filling

True

**Question 7**

1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?

In [41]:
# Get all options located on Islands
df_island = df[df['ocean_proximity'] == 'ISLAND']
df_island

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [71]:
# Select special columns
island_columns = df_island[['housing_median_age', 'total_rooms', 'total_bedrooms']]
island_columns

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [73]:
# Convert the DataFrame to a NumPy array
X = island_columns.to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [74]:
# Compute matrix-matrix multiplication
XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [75]:
# Compute the inverse of XTX
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [76]:
# Create y array
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [77]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y
w = np.dot(np.dot(XTX_inverse, X.T), y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [78]:
# Get last element of w
last_element_of_w = w[-1]
last_element_of_w

5.699229455065594